//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketService
    {
        public int Id { get; set; }
        public Nullable<int> PacketId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual FService FService { get; set; }
        public virtual Packet Packet { get; set; }
    }
}
